services:
  - type: web
    name: hospital-management
    runtime: java
    buildCommand: mvn clean install -DskipTests
    startCommand: java -Dspring.profiles.active=prod -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
